//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace PgDbase.models
{
	/// <summary>
	/// Database       : portal
	/// Data Source    : chuvashia.com
	/// Server Version : 9.5.5
	/// </summary>
	public partial class CMSdb : LinqToDB.Data.DataConnection
	{
		public ITable<core_cms_menu_groups>        core_cms_menu_groups        { get { return this.GetTable<core_cms_menu_groups>(); } }
		public ITable<core_cms_menus>              core_cms_menus              { get { return this.GetTable<core_cms_menus>(); } }
		public ITable<core_controller>             core_controller             { get { return this.GetTable<core_controller>(); } }
		public ITable<core_log>                    core_log                    { get { return this.GetTable<core_log>(); } }
		public ITable<core_log_actions>            core_log_actions            { get { return this.GetTable<core_log_actions>(); } }
		public ITable<core_log_sections>           core_log_sections           { get { return this.GetTable<core_log_sections>(); } }
		public ITable<core_material>               core_material               { get { return this.GetTable<core_material>(); } }
		public ITable<core_material_categories>    core_material_categories    { get { return this.GetTable<core_material_categories>(); } }
		public ITable<core_material_category_link> core_material_category_link { get { return this.GetTable<core_material_category_link>(); } }
		public ITable<core_page>                   core_page                   { get { return this.GetTable<core_page>(); } }
		public ITable<core_resolution_groups>      core_resolution_groups      { get { return this.GetTable<core_resolution_groups>(); } }
		public ITable<core_resolution_user>        core_resolution_user        { get { return this.GetTable<core_resolution_user>(); } }
		public ITable<core_site>                   core_site                   { get { return this.GetTable<core_site>(); } }
		public ITable<core_sites_controllers>      core_sites_controllers      { get { return this.GetTable<core_sites_controllers>(); } }
		public ITable<core_sites_domains>          core_sites_domains          { get { return this.GetTable<core_sites_domains>(); } }
		public ITable<core_user>                   core_user                   { get { return this.GetTable<core_user>(); } }
		public ITable<core_user_group>             core_user_group             { get { return this.GetTable<core_user_group>(); } }
		public ITable<core_user_site_link>         core_user_site_link         { get { return this.GetTable<core_user_site_link>(); } }
		public ITable<core_view>                   core_view                   { get { return this.GetTable<core_view>(); } }

		public CMSdb()
			: base("CMSdb")
		{
			InitDataContext();
		}

		public CMSdb(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table(Schema="core", Name="cms_menu_groups")]
	public partial class core_cms_menu_groups
	{
		[PrimaryKey, Identity   ] public int    id      { get; set; } // integer
		[Column,     NotNull    ] public string c_title { get; set; } // character varying(32)
		[Column,        Nullable] public string c_alias { get; set; } // character varying(16)

		#region Associations

		/// <summary>
		/// fk_cms_menu_cms_menu_group_BackReference
		/// </summary>
		[Association(ThisKey="c_alias", OtherKey="f_menu_group", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<core_cms_menus> fkcmsmenucmsmenugroups { get; set; }

		#endregion
	}

	[Table(Schema="core", Name="cms_menus")]
	public partial class core_cms_menus
	{
		[PrimaryKey, NotNull    ] public Guid   id           { get; set; } // uuid
		[Column,        Nullable] public string c_title      { get; set; } // character varying(128)
		[Column,     NotNull    ] public string c_alias      { get; set; } // character varying(32)
		[Column,        Nullable] public string c_class      { get; set; } // character varying(50)
		[Column,        Nullable] public string f_menu_group { get; set; } // character varying(16)
		[Column,        Nullable] public int?   n_sort       { get; set; } // integer

		#region Associations

		/// <summary>
		/// fk_cms_menu_cms_menu_group
		/// </summary>
		[Association(ThisKey="f_menu_group", OtherKey="c_alias", CanBeNull=true, KeyName="fk_cms_menu_cms_menu_group", BackReferenceName="fkcmsmenucmsmenugroups")]
		public core_cms_menu_groups fkcmsmenucmsmenugroup { get; set; }

		/// <summary>
		/// fk_resolution_group_cms_menu_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_cmsmenu", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<core_resolution_groups> fkresolutiongroupcmsmenus { get; set; }

		#endregion
	}

	[Table(Schema="core", Name="controllers")]
	public partial class core_controller
	{
		[PrimaryKey, Identity   ] public int    id                { get; set; } // integer
		[Column,        Nullable] public int?   pid               { get; set; } // integer
		[Column,        Nullable] public string c_name            { get; set; } // character varying(128)
		[Column,     NotNull    ] public string c_controller_name { get; set; } // character varying(128)
		[Column,        Nullable] public string c_action_name     { get; set; } // character varying(128)
		[Column,     NotNull    ] public Guid   c_default_view    { get; set; } // uuid

		#region Associations

		/// <summary>
		/// fk_controller_id_pid
		/// </summary>
		[Association(ThisKey="pid", OtherKey="id", CanBeNull=true, KeyName="fk_controller_id_pid", BackReferenceName="fk_controller_id_pid_BackReferences")]
		public core_controller fkcontrolleridpid { get; set; }

		/// <summary>
		/// fk_site_to_controllers_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_controller", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<core_sites_controllers> fksitetoes { get; set; }

		/// <summary>
		/// fk_controller_id_pid_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="pid", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<core_controller> fk_controller_id_pid_BackReferences { get; set; }

		#endregion
	}

	[Table(Schema="core", Name="logs")]
	public partial class core_log
	{
		[PrimaryKey, NotNull    ] public Guid     id            { get; set; } // uuid
		[Column,     NotNull    ] public Guid     f_page        { get; set; } // uuid
		[Column,        Nullable] public string   c_page_name   { get; set; } // character varying(512)
		[Column,        Nullable] public Guid?    f_site        { get; set; } // uuid
		[Column,     NotNull    ] public string   f_logsections { get; set; } // character varying(64)
		[Column,     NotNull    ] public Guid     f_user        { get; set; } // uuid
		[Column,     NotNull    ] public DateTime d_date        { get; set; } // timestamp (6) without time zone
		[Column,     NotNull    ] public string   f_action      { get; set; } // character varying(32)
		[Column,     NotNull    ] public string   c_ip          { get; set; } // character varying(16)
		[Column,        Nullable] public object   c_json        { get; set; } // json

		#region Associations

		/// <summary>
		/// fk_log_users
		/// </summary>
		[Association(ThisKey="f_user", OtherKey="id", CanBeNull=false, KeyName="fk_log_users", BackReferenceName="fklogs")]
		public core_user fkloguser { get; set; }

		/// <summary>
		/// fk_log_log_sections
		/// </summary>
		[Association(ThisKey="f_logsections", OtherKey="c_alias", CanBeNull=false, KeyName="fk_log_log_sections", BackReferenceName="fkloglogsections")]
		public core_log_sections fkloglogsection { get; set; }

		/// <summary>
		/// fk_log_log_action
		/// </summary>
		[Association(ThisKey="f_action", OtherKey="c_action", CanBeNull=false, KeyName="fk_log_log_action", BackReferenceName="fkloglogactions")]
		public core_log_actions fkloglogaction { get; set; }

		#endregion
	}

	[Table(Schema="core", Name="log_actions")]
	public partial class core_log_actions
	{
		[PrimaryKey, NotNull    ] public string c_action      { get; set; } // character varying(32)
		[Column,        Nullable] public string c_action_name { get; set; } // character varying(100)

		#region Associations

		/// <summary>
		/// fk_log_log_action_BackReference
		/// </summary>
		[Association(ThisKey="c_action", OtherKey="f_action", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<core_log> fkloglogactions { get; set; }

		#endregion
	}

	[Table(Schema="core", Name="log_sections")]
	public partial class core_log_sections
	{
		[PrimaryKey, NotNull] public string c_alias        { get; set; } // character varying(64)
		[Column,     NotNull] public string c_section_name { get; set; } // character varying(64)

		#region Associations

		/// <summary>
		/// fk_log_log_sections_BackReference
		/// </summary>
		[Association(ThisKey="c_alias", OtherKey="f_logsections", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<core_log> fkloglogsections { get; set; }

		#endregion
	}

	[Table(Schema="core", Name="materials")]
	public partial class core_material
	{
		[Identity               ] public int      id            { get; set; } // integer
		[PrimaryKey, NotNull    ] public Guid     gid           { get; set; } // uuid
		[Column,     NotNull    ] public DateTime d_date        { get; set; } // timestamp (6) without time zone
		[Column,     NotNull    ] public string   c_name        { get; set; } // character varying(512)
		[Column,        Nullable] public string   c_text        { get; set; } // text
		[Column,        Nullable] public string   c_photo       { get; set; } // character varying(512)
		[Column,        Nullable] public string   c_keyw        { get; set; } // character varying(256)
		[Column,        Nullable] public string   c_desc        { get; set; } // character varying(512)
		[Column,        Nullable] public string   c_source_url  { get; set; } // character varying(512)
		[Column,        Nullable] public string   c_source_name { get; set; } // character varying(128)
		[Column,        Nullable] public int?     c_view_count  { get; set; } // integer
		[Column,        Nullable] public bool?    b_disabled    { get; set; } // boolean
		[Column,        Nullable] public bool?    b_important   { get; set; } // boolean
		[Column,     NotNull    ] public Guid     f_site        { get; set; } // uuid

		#region Associations

		/// <summary>
		/// fk_materials_sites
		/// </summary>
		[Association(ThisKey="f_site", OtherKey="id", CanBeNull=false, KeyName="fk_materials_sites", BackReferenceName="fkmaterials")]
		public core_site fksite { get; set; }

		/// <summary>
		/// fk_materials_categories_link_BackReference
		/// </summary>
		[Association(ThisKey="gid", OtherKey="f_materials", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<core_material_category_link> fkcategorieslinks { get; set; }

		#endregion
	}

	[Table(Schema="core", Name="material_categories")]
	public partial class core_material_categories
	{
		[PrimaryKey, NotNull] public Guid   id      { get; set; } // uuid
		[Column,     NotNull] public string c_name  { get; set; } // character varying(128)
		[Column,     NotNull] public string c_alias { get; set; } // character varying
		[Column,     NotNull] public int    n_sort  { get; set; } // integer
		[Column,     NotNull] public Guid   f_site  { get; set; } // uuid

		#region Associations

		/// <summary>
		/// fk_materials_categories_sites
		/// </summary>
		[Association(ThisKey="f_site", OtherKey="id", CanBeNull=false, KeyName="fk_materials_categories_sites", BackReferenceName="fkmaterialscategories")]
		public core_site fkmaterialscategoriessite { get; set; }

		/// <summary>
		/// fk_materials_categories_link_f_mk_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_maaterials_category", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<core_material_category_link> fkmaterialscategorieslinkfmks { get; set; }

		#endregion
	}

	[Table(Schema="core", Name="material_category_link")]
	public partial class core_material_category_link
	{
		[PrimaryKey, NotNull    ] public Guid  id                    { get; set; } // uuid
		[Column,        Nullable] public Guid? f_materials           { get; set; } // uuid
		[Column,        Nullable] public Guid? f_maaterials_category { get; set; } // uuid

		#region Associations

		/// <summary>
		/// fk_materials_categories_link_f_mk
		/// </summary>
		[Association(ThisKey="f_maaterials_category", OtherKey="id", CanBeNull=true, KeyName="fk_materials_categories_link_f_mk", BackReferenceName="fkmaterialscategorieslinkfmks")]
		public core_material_categories fkmaterialscategorieslinkfmk { get; set; }

		/// <summary>
		/// fk_materials_categories_link
		/// </summary>
		[Association(ThisKey="f_materials", OtherKey="gid", CanBeNull=true, KeyName="fk_materials_categories_link", BackReferenceName="fkcategorieslinks")]
		public core_material fkmaterialscategorieslink { get; set; }

		#endregion
	}

	[Table(Schema="core", Name="pages")]
	public partial class core_page
	{
		[PrimaryKey, NotNull    ] public Guid   gid                { get; set; } // uuid
		[Column,     NotNull    ] public string c_name             { get; set; } // character varying(512)
		[Column,        Nullable] public Guid?  pgid               { get; set; } // uuid
		[Column,        Nullable] public string c_path             { get; set; } // character varying(1024)
		[Column,        Nullable] public string c_alias            { get; set; } // character varying(128)
		[Column,        Nullable] public string c_text             { get; set; } // text
		[Column,        Nullable] public string c_url              { get; set; } // character varying(256)
		[Column,     NotNull    ] public int    n_sort             { get; set; } // integer
		[Column,     NotNull    ] public Guid   f_site             { get; set; } // uuid
		[Column,        Nullable] public bool?  b_disabled         { get; set; } // boolean
		[Column,        Nullable] public string c_keyw             { get; set; } // character varying(512)
		[Column,        Nullable] public string c_desc             { get; set; } // character varying(1024)
		[Column,        Nullable] public int?   f_sites_controller { get; set; } // integer

		#region Associations

		/// <summary>
		/// fk_page_sites_contreller
		/// </summary>
		[Association(ThisKey="f_sites_controller", OtherKey="id", CanBeNull=true, KeyName="fk_page_sites_contreller", BackReferenceName="fkpagesitescontrellers")]
		public core_sites_controllers fkpagesitescontreller { get; set; }

		/// <summary>
		/// fk_page_sites
		/// </summary>
		[Association(ThisKey="f_site", OtherKey="id", CanBeNull=false, KeyName="fk_page_sites", BackReferenceName="fkpages")]
		public core_site fkpagesite { get; set; }

		/// <summary>
		/// fk_page_page
		/// </summary>
		[Association(ThisKey="gid", OtherKey="pgid", CanBeNull=false, KeyName="fk_page_page", BackReferenceName="fk_page_page_BackReference")]
		public core_page fkpagepage { get; set; }

		/// <summary>
		/// fk_page_page_BackReference
		/// </summary>
		[Association(ThisKey="pgid", OtherKey="gid", CanBeNull=true, IsBackReference=true)]
		public core_page fk_page_page_BackReference { get; set; }

		#endregion
	}

	[Table(Schema="core", Name="resolution_groups")]
	public partial class core_resolution_groups
	{
		[PrimaryKey, Identity   ] public int   id          { get; set; } // integer
		[Column,        Nullable] public Guid? f_usergroup { get; set; } // uuid
		[Column,        Nullable] public bool? b_read      { get; set; } // boolean
		[Column,        Nullable] public bool? b_write     { get; set; } // boolean
		[Column,        Nullable] public bool? b_change    { get; set; } // boolean
		[Column,        Nullable] public bool? b_delete    { get; set; } // boolean
		[Column,     NotNull    ] public Guid  f_cmsmenu   { get; set; } // uuid

		#region Associations

		/// <summary>
		/// fk_resolution_group_cms_menu
		/// </summary>
		[Association(ThisKey="f_cmsmenu", OtherKey="id", CanBeNull=false, KeyName="fk_resolution_group_cms_menu", BackReferenceName="fkresolutiongroupcmsmenus")]
		public core_cms_menus fkresolutiongroupcmsmenu { get; set; }

		/// <summary>
		/// fk_resolution_group_user_group
		/// </summary>
		[Association(ThisKey="f_usergroup", OtherKey="id", CanBeNull=true, KeyName="fk_resolution_group_user_group", BackReferenceName="fkresolutiongroupusergroups")]
		public core_user_group fkresolutiongroupusergroup { get; set; }

		#endregion
	}

	[Table(Schema="core", Name="resolution_user")]
	public partial class core_resolution_user
	{
		[PrimaryKey, NotNull    ] public Guid  id                 { get; set; } // uuid
		[Column,        Nullable] public Guid? f_usersitelink     { get; set; } // uuid
		[Column,     NotNull    ] public int   f_sites_controller { get; set; } // integer
		[Column,        Nullable] public bool? b_read             { get; set; } // boolean
		[Column,        Nullable] public bool? b_write            { get; set; } // boolean
		[Column,        Nullable] public bool? b_change           { get; set; } // boolean
		[Column,        Nullable] public bool? b_delete           { get; set; } // boolean

		#region Associations

		/// <summary>
		/// fk_resolution_user_stescontroller
		/// </summary>
		[Association(ThisKey="f_sites_controller", OtherKey="id", CanBeNull=false, KeyName="fk_resolution_user_stescontroller", BackReferenceName="fkresolutionuserstescontrollers")]
		public core_sites_controllers fkresolutionuserstescontroller { get; set; }

		/// <summary>
		/// fk_resolution_user
		/// </summary>
		[Association(ThisKey="f_usersitelink", OtherKey="id", CanBeNull=true, KeyName="fk_resolution_user", BackReferenceName="fkresolutionusers")]
		public core_user_site_link fkresolutionuser { get; set; }

		#endregion
	}

	[Table(Schema="core", Name="sites")]
	public partial class core_site
	{
		[PrimaryKey, NotNull] public Guid   id         { get; set; } // uuid
		[Column,     NotNull] public string c_name     { get; set; } // character varying(512)
		[Column,     NotNull] public bool   b_disabled { get; set; } // boolean

		#region Associations

		/// <summary>
		/// fk_controllers_to_site_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_site", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<core_sites_controllers> fkcontrollerstosites { get; set; }

		/// <summary>
		/// fk_sites_domains_sites_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_site", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<core_sites_domains> fkdomains { get; set; }

		/// <summary>
		/// fk_materials_sites_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_site", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<core_material> fkmaterials { get; set; }

		/// <summary>
		/// fk_page_sites_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_site", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<core_page> fkpages { get; set; }

		/// <summary>
		/// fk_user_site_link_sites_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_site", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<core_user_site_link> fkusersitelinks { get; set; }

		/// <summary>
		/// fk_materials_categories_sites_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_site", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<core_material_categories> fkmaterialscategories { get; set; }

		#endregion
	}

	[Table(Schema="core", Name="sites_controllers")]
	public partial class core_sites_controllers
	{
		[PrimaryKey, Identity] public int  id           { get; set; } // integer
		[Column,     NotNull ] public Guid f_site       { get; set; } // uuid
		[Column,     NotNull ] public int  f_controller { get; set; } // integer
		[Column,     NotNull ] public int  f_view       { get; set; } // integer

		#region Associations

		/// <summary>
		/// fk_controllers_to_site
		/// </summary>
		[Association(ThisKey="f_site", OtherKey="id", CanBeNull=false, KeyName="fk_controllers_to_site", BackReferenceName="fkcontrollerstosites")]
		public core_site fkcontrollerstosite { get; set; }

		/// <summary>
		/// fk_site_to_controllers
		/// </summary>
		[Association(ThisKey="f_controller", OtherKey="id", CanBeNull=false, KeyName="fk_site_to_controllers", BackReferenceName="fksitetoes")]
		public core_controller fksitetocontroller { get; set; }

		/// <summary>
		/// fk_view_to_site
		/// </summary>
		[Association(ThisKey="f_view", OtherKey="id", CanBeNull=false, KeyName="fk_view_to_site", BackReferenceName="fkviewtosites")]
		public core_view fkviewtosite { get; set; }

		/// <summary>
		/// fk_page_sites_contreller_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_sites_controller", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<core_page> fkpagesitescontrellers { get; set; }

		/// <summary>
		/// fk_resolution_user_stescontroller_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_sites_controller", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<core_resolution_user> fkresolutionuserstescontrollers { get; set; }

		#endregion
	}

	[Table(Schema="core", Name="sites_domains")]
	public partial class core_sites_domains
	{
		[PrimaryKey, Identity   ] public int    id        { get; set; } // integer
		[Column,        Nullable] public Guid?  f_site    { get; set; } // uuid
		[Column,     NotNull    ] public string c_domain  { get; set; } // character varying(256)
		[Column,     NotNull    ] public bool   b_default { get; set; } // boolean

		#region Associations

		/// <summary>
		/// fk_sites_domains_sites
		/// </summary>
		[Association(ThisKey="f_site", OtherKey="id", CanBeNull=true, KeyName="fk_sites_domains_sites", BackReferenceName="fkdomains")]
		public core_site fksitesdomainssite { get; set; }

		#endregion
	}

	[Table(Schema="core", Name="users")]
	public partial class core_user
	{
		[PrimaryKey, NotNull    ] public Guid      id                 { get; set; } // uuid
		[Column,        Nullable] public string    c_email            { get; set; } // character varying(128)
		[Column,        Nullable] public string    c_salt             { get; set; } // character varying(32)
		[Column,        Nullable] public string    c_hash             { get; set; } // character varying(128)
		[Column,        Nullable] public Guid?     c_change_pass_code { get; set; } // uuid
		[Column,     NotNull    ] public string    c_surname          { get; set; } // character varying(128)
		[Column,     NotNull    ] public string    c_name             { get; set; } // character varying(128)
		[Column,        Nullable] public string    c_patronymic       { get; set; } // character varying(128)
		[Column,     NotNull    ] public bool      b_disabled         { get; set; } // boolean
		[Column,     NotNull    ] public int       n_error_count      { get; set; } // integer
		[Column,        Nullable] public DateTime? d_try_login        { get; set; } // timestamp (6) without time zone

		#region Associations

		/// <summary>
		/// fk_user_site_link_users_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_user", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<core_user_site_link> fkusersitelinks { get; set; }

		/// <summary>
		/// fk_log_users_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_user", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<core_log> fklogs { get; set; }

		#endregion
	}

	[Table(Schema="core", Name="user_group")]
	public partial class core_user_group
	{
		[PrimaryKey, NotNull] public Guid   id      { get; set; } // uuid
		[Column,     NotNull] public string c_title { get; set; } // character varying(128)
		[Column,     NotNull] public string c_alias { get; set; } // character varying(32)

		#region Associations

		/// <summary>
		/// fk_user_site_link_user_group_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_user_group", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<core_user_site_link> fkusersitelinkusergroups { get; set; }

		/// <summary>
		/// fk_resolution_group_user_group_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_usergroup", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<core_resolution_groups> fkresolutiongroupusergroups { get; set; }

		#endregion
	}

	[Table(Schema="core", Name="user_site_link")]
	public partial class core_user_site_link
	{
		[PrimaryKey, NotNull] public Guid id           { get; set; } // uuid
		[Column,     NotNull] public Guid f_site       { get; set; } // uuid
		[Column,     NotNull] public Guid f_user       { get; set; } // uuid
		[Column,     NotNull] public Guid f_user_group { get; set; } // uuid

		#region Associations

		/// <summary>
		/// fk_user_site_link_user_group
		/// </summary>
		[Association(ThisKey="f_user_group", OtherKey="id", CanBeNull=false, KeyName="fk_user_site_link_user_group", BackReferenceName="fkusersitelinkusergroups")]
		public core_user_group fkusersitelinkusergroup { get; set; }

		/// <summary>
		/// fk_user_site_link_users
		/// </summary>
		[Association(ThisKey="f_user", OtherKey="id", CanBeNull=false, KeyName="fk_user_site_link_users", BackReferenceName="fkusersitelinks")]
		public core_user fkusersitelinkuser { get; set; }

		/// <summary>
		/// fk_user_site_link_sites
		/// </summary>
		[Association(ThisKey="f_site", OtherKey="id", CanBeNull=false, KeyName="fk_user_site_link_sites", BackReferenceName="fkusersitelinks")]
		public core_site fkusersitelinksite { get; set; }

		/// <summary>
		/// fk_resolution_user_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_usersitelink", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<core_resolution_user> fkresolutionusers { get; set; }

		#endregion
	}

	[Table(Schema="core", Name="views")]
	public partial class core_view
	{
		[PrimaryKey, Identity   ] public int    id           { get; set; } // integer
		[Column,     NotNull    ] public string c_name       { get; set; } // character varying(128)
		[Column,        Nullable] public int?   f_controller { get; set; } // integer
		[Column,     NotNull    ] public string c_path       { get; set; } // character varying(512)

		#region Associations

		/// <summary>
		/// fk_view_to_site_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_view", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<core_sites_controllers> fkviewtosites { get; set; }

		#endregion
	}

	public static partial class TableExtensions
	{
		public static core_cms_menu_groups Find(this ITable<core_cms_menu_groups> table, int id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static core_cms_menus Find(this ITable<core_cms_menus> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static core_controller Find(this ITable<core_controller> table, int id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static core_log Find(this ITable<core_log> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static core_log_actions Find(this ITable<core_log_actions> table, string c_action)
		{
			return table.FirstOrDefault(t =>
				t.c_action == c_action);
		}

		public static core_log_sections Find(this ITable<core_log_sections> table, string c_alias)
		{
			return table.FirstOrDefault(t =>
				t.c_alias == c_alias);
		}

		public static core_material Find(this ITable<core_material> table, Guid gid)
		{
			return table.FirstOrDefault(t =>
				t.gid == gid);
		}

		public static core_material_categories Find(this ITable<core_material_categories> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static core_material_category_link Find(this ITable<core_material_category_link> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static core_page Find(this ITable<core_page> table, Guid gid)
		{
			return table.FirstOrDefault(t =>
				t.gid == gid);
		}

		public static core_resolution_groups Find(this ITable<core_resolution_groups> table, int id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static core_resolution_user Find(this ITable<core_resolution_user> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static core_site Find(this ITable<core_site> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static core_sites_controllers Find(this ITable<core_sites_controllers> table, int id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static core_sites_domains Find(this ITable<core_sites_domains> table, int id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static core_user Find(this ITable<core_user> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static core_user_group Find(this ITable<core_user_group> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static core_user_site_link Find(this ITable<core_user_site_link> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static core_view Find(this ITable<core_view> table, int id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}
	}
}
  
