
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD200:Use \"Async\" suffix in names of Task-returning methods.", Justification = "<Pending>", Scope = "member", Target = "~M:Portal.Areas.Admin.Controllers.SiteUsersController.Delete(System.Guid)~System.Threading.Tasks.Task{System.Web.Mvc.ActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD200:Use \"Async\" suffix in names of Task-returning methods.", Justification = "<Pending>", Scope = "member", Target = "~M:Portal.Areas.Admin.Controllers.SiteUsersController.Save(System.Guid,Portal.Areas.Admin.Models.UsersViewModel)~System.Threading.Tasks.Task{System.Web.Mvc.ActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD200:Use \"Async\" suffix in names of Task-returning methods.", Justification = "<Pending>", Scope = "member", Target = "~M:Portal.Controllers.AccountController.ConfirmEmail(System.String,System.String)~System.Threading.Tasks.Task{System.Web.Mvc.ActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD200:Use \"Async\" suffix in names of Task-returning methods.", Justification = "<Pending>", Scope = "member", Target = "~M:Portal.Controllers.AccountController.ExternalLoginCallback(System.String)~System.Threading.Tasks.Task{System.Web.Mvc.ActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD200:Use \"Async\" suffix in names of Task-returning methods.", Justification = "<Pending>", Scope = "member", Target = "~M:Portal.Controllers.AccountController.ExternalLoginConfirmation(Portal.Models.ExternalLoginConfirmationViewModel,System.String)~System.Threading.Tasks.Task{System.Web.Mvc.ActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD200:Use \"Async\" suffix in names of Task-returning methods.", Justification = "<Pending>", Scope = "member", Target = "~M:Portal.Controllers.AccountController.ForgotPassword(Portal.Models.ForgotPasswordViewModel)~System.Threading.Tasks.Task{System.Web.Mvc.ActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD200:Use \"Async\" suffix in names of Task-returning methods.", Justification = "<Pending>", Scope = "member", Target = "~M:Portal.Controllers.AccountController.Login(Portal.Models.LoginViewModel,System.String)~System.Threading.Tasks.Task{System.Web.Mvc.ActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD200:Use \"Async\" suffix in names of Task-returning methods.", Justification = "<Pending>", Scope = "member", Target = "~M:Portal.Controllers.AccountController.Register(Portal.Models.RegisterViewModel)~System.Threading.Tasks.Task{System.Web.Mvc.ActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD200:Use \"Async\" suffix in names of Task-returning methods.", Justification = "<Pending>", Scope = "member", Target = "~M:Portal.Controllers.AccountController.ResetPassword(Portal.Models.ResetPasswordViewModel)~System.Threading.Tasks.Task{System.Web.Mvc.ActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD200:Use \"Async\" suffix in names of Task-returning methods.", Justification = "<Pending>", Scope = "member", Target = "~M:Portal.Controllers.AccountController.SendCode(Portal.Models.SendCodeViewModel)~System.Threading.Tasks.Task{System.Web.Mvc.ActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD200:Use \"Async\" suffix in names of Task-returning methods.", Justification = "<Pending>", Scope = "member", Target = "~M:Portal.Controllers.AccountController.SendCode(System.String,System.Boolean)~System.Threading.Tasks.Task{System.Web.Mvc.ActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD200:Use \"Async\" suffix in names of Task-returning methods.", Justification = "<Pending>", Scope = "member", Target = "~M:Portal.Controllers.AccountController.VerifyCode(Portal.Models.VerifyCodeViewModel)~System.Threading.Tasks.Task{System.Web.Mvc.ActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD200:Use \"Async\" suffix in names of Task-returning methods.", Justification = "<Pending>", Scope = "member", Target = "~M:Portal.Controllers.AccountController.VerifyCode(System.String,System.String,System.Boolean)~System.Threading.Tasks.Task{System.Web.Mvc.ActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD200:Use \"Async\" suffix in names of Task-returning methods.", Justification = "<Pending>", Scope = "member", Target = "~M:Portal.Controllers.AccountManageController.AddPhoneNumber(Portal.Models.AddPhoneNumberViewModel)~System.Threading.Tasks.Task{System.Web.Mvc.ActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD200:Use \"Async\" suffix in names of Task-returning methods.", Justification = "<Pending>", Scope = "member", Target = "~M:Portal.Controllers.AccountManageController.ChangePassword(Portal.Models.ChangePasswordViewModel)~System.Threading.Tasks.Task{System.Web.Mvc.ActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD200:Use \"Async\" suffix in names of Task-returning methods.", Justification = "<Pending>", Scope = "member", Target = "~M:Portal.Controllers.AccountManageController.DisableTwoFactorAuthentication~System.Threading.Tasks.Task{System.Web.Mvc.ActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD200:Use \"Async\" suffix in names of Task-returning methods.", Justification = "<Pending>", Scope = "member", Target = "~M:Portal.Controllers.AccountManageController.EnableTwoFactorAuthentication~System.Threading.Tasks.Task{System.Web.Mvc.ActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD200:Use \"Async\" suffix in names of Task-returning methods.", Justification = "<Pending>", Scope = "member", Target = "~M:Portal.Controllers.AccountManageController.Index(System.Nullable{Portal.Controllers.AccountManageController.ManageMessageId})~System.Threading.Tasks.Task{System.Web.Mvc.ActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD200:Use \"Async\" suffix in names of Task-returning methods.", Justification = "<Pending>", Scope = "member", Target = "~M:Portal.Controllers.AccountManageController.LinkLoginCallback~System.Threading.Tasks.Task{System.Web.Mvc.ActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD200:Use \"Async\" suffix in names of Task-returning methods.", Justification = "<Pending>", Scope = "member", Target = "~M:Portal.Controllers.AccountManageController.ManageLogins(System.Nullable{Portal.Controllers.AccountManageController.ManageMessageId})~System.Threading.Tasks.Task{System.Web.Mvc.ActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD200:Use \"Async\" suffix in names of Task-returning methods.", Justification = "<Pending>", Scope = "member", Target = "~M:Portal.Controllers.AccountManageController.RemoveLogin(System.String,System.String)~System.Threading.Tasks.Task{System.Web.Mvc.ActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD200:Use \"Async\" suffix in names of Task-returning methods.", Justification = "<Pending>", Scope = "member", Target = "~M:Portal.Controllers.AccountManageController.RemovePhoneNumber~System.Threading.Tasks.Task{System.Web.Mvc.ActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD200:Use \"Async\" suffix in names of Task-returning methods.", Justification = "<Pending>", Scope = "member", Target = "~M:Portal.Controllers.AccountManageController.SetPassword(Portal.Models.SetPasswordViewModel)~System.Threading.Tasks.Task{System.Web.Mvc.ActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD200:Use \"Async\" suffix in names of Task-returning methods.", Justification = "<Pending>", Scope = "member", Target = "~M:Portal.Controllers.AccountManageController.VerifyPhoneNumber(Portal.Models.VerifyPhoneNumberViewModel)~System.Threading.Tasks.Task{System.Web.Mvc.ActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD200:Use \"Async\" suffix in names of Task-returning methods.", Justification = "<Pending>", Scope = "member", Target = "~M:Portal.Controllers.AccountManageController.VerifyPhoneNumber(System.String)~System.Threading.Tasks.Task{System.Web.Mvc.ActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD200:Use \"Async\" suffix in names of Task-returning methods.", Justification = "<Pending>", Scope = "member", Target = "~M:Portal.Controllers.WidgetController.ChangePassword(Portal.Models.ChangePasswordFrontModel)~System.Threading.Tasks.Task{System.Web.Mvc.ActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD200:Use \"Async\" suffix in names of Task-returning methods.", Justification = "<Pending>", Scope = "member", Target = "~M:Portal.Controllers.WidgetController.ChangeUserInfo(PgDbase.entity.UserModelUpdate)~System.Threading.Tasks.Task{System.Web.Mvc.ActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope = "member", Target = "Mailer.#DislyEvent")]

